// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAtrCmdeBjKJNtagDyikeQ50lXg-78sA',
    appId: '1:955799194825:web:a4205bbdb6aeb62ce49118',
    messagingSenderId: '955799194825',
    projectId: 'final-project-6b3e9',
    authDomain: 'final-project-6b3e9.firebaseapp.com',
    databaseURL: 'https://final-project-6b3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-6b3e9.appspot.com',
    measurementId: 'G-W3SVRE01F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5m75msA1G8HDZ_GETdnacwDQrLfwe94s',
    appId: '1:955799194825:android:da2956d65d3c96afe49118',
    messagingSenderId: '955799194825',
    projectId: 'final-project-6b3e9',
    databaseURL: 'https://final-project-6b3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-6b3e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhqtqXSE_DS_DhlTk-ZVNBPJaYOGIn6sc',
    appId: '1:955799194825:ios:ba20e8a5b75fcdf2e49118',
    messagingSenderId: '955799194825',
    projectId: 'final-project-6b3e9',
    databaseURL: 'https://final-project-6b3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-6b3e9.appspot.com',
    iosClientId: '955799194825-revq4n1jv94o6gi27adsioj5p4h79r07.apps.googleusercontent.com',
    iosBundleId: 'com.example.alert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhqtqXSE_DS_DhlTk-ZVNBPJaYOGIn6sc',
    appId: '1:955799194825:ios:ba20e8a5b75fcdf2e49118',
    messagingSenderId: '955799194825',
    projectId: 'final-project-6b3e9',
    databaseURL: 'https://final-project-6b3e9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-project-6b3e9.appspot.com',
    iosClientId: '955799194825-revq4n1jv94o6gi27adsioj5p4h79r07.apps.googleusercontent.com',
    iosBundleId: 'com.example.alert',
  );
}
